# Generated by Django 5.2.1 on 2025-05-13 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_blog_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='blog_post',
        ),
    ]
