# Generated by Django 5.2.1 on 2025-05-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_blog_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='slug',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
