# Generated by Django 5.2.1 on 2025-05-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_blog_post_slug_alter_blog_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
