# Generated by Django 5.2.1 on 2025-05-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
