# Generated by Django 5.2.1 on 2025-05-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_category_blog_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='service_img/')),
                ('heading', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=400)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
    ]
