# Generated by Django 5.2.1 on 2025-05-18 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='service',
            new_name='myservice',
        ),
    ]
