# Generated by Django 5.2.1 on 2025-05-20 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_faq'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='faq',
            new_name='faqs',
        ),
    ]
