# Generated by Django 5.2.1 on 2025-06-07 10:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_rename_faq_faqs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
