# Generated by Django 5.2.1 on 2025-06-07 18:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_alter_blog_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myservice',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
