# Generated by Django 5.2.1 on 2025-06-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_myservice_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='myservice',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
