# Generated by Django 5.2.1 on 2025-06-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_myservice_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myservice',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
